algoritmo "MostrarNome"
// aula 1 input, output e processo
var
// texto - caractere - string
//verdadeiro/falso - logico - bolean
// numero inteiro- inteiro - int
// numero decimal - real - flat - float
nomeUsuario : caractere

inicio
// outupt - saida - telas,led , reposta por voz , som
// l - line break - quebra de linha
//nomeusuario <- '' Filipe''
   escreva(" oi, ")
escreva(" bom dia" +nomeusuario)
//leia(nomeusuario)

fimalgoritmo // Adicionei 'fimalgoritmo' que estava faltando